### ISSUE TITLE
博客notes文章中添加笔记评论仓库

### ISSUE THREAD

**Issue by VicoGao15** [VicoBlog/Notes#3]
1、指定repo: vicoblog/notes：  
```
---
wiki: notes
menu_id: notes
title: notes「笔记」栏目
date: 2024-08-16 16:47:19
banner: cover/notes.jpg
comments: false
beaudar:
    repo: vicoblog/notes
    issue-term: pathname
    theme: preferred-color-scheme
    label:
    input-position: top # top/bottom 评论框位置
    comment-order: desc # desc 排序
    keep-theme: # true/false
    loading: false
    branch: main
---
```
2、博客下面评论后，在issue中会单独根据每个文章生成记录，不是单纯的笔记
，所以移除笔记下面的博客评论`comments: false`，只在github issue上新增。
